version: "3.7"

services:
  database_queries_challenge:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: ignite-challenge-database-queries
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app 
    links:
      -  database_queries_challenge
    depends_on: 
      -  database_queries_challenge

volumes:
  pgdata:
    driver: local